# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GilvBx80q2Oypk9fH_lOFFtnlUm3gY6R
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

data=pd.read_csv('Salary_Data.csv')

data.head()

X=data.iloc[:,:1]

y=data.iloc[:,-1]

from sklearn.linear_model import LinearRegression

lr=LinearRegression()

lr.fit(X,y)

pickle.dump(lr,open('model.pkl','wb'))

model=pickle.load(open('model.pkl','rb'))

print(model.predict([[4]]))

